---
title: 'The Political Economy of Public Banks'
subtitle: 'Electoral Effects of Savings Banks in German Subnational Politics - The Case of Bavaria'
author: |
        | Jonas Markgraf & Malte Berneaud-Kötz
        | Hertie School of Governance
output: 
  html_document:
    toc: true
    toc_float:
      smooth_scroll: true
      collapsed: true
    theme: journal
    highlight: monochrome
---

## Abstract

This paper aims to **estimate the effect of board membership in German *Sparkassen* (public savings banks) on politicians' success in local elections**. For this purpose, we exploit the fact that not all locally elected political leaders in Germany are board members in savings banks and compare electoral performance of politicians with and without participation in savings bank’s Board of Directors.
The paper contributes to the Public Economics literature on *electoral credit cycles* that argues that public banks increase lending in years preceeding elections and to the Political Science debate on the *incumbency advantage* that politicians appear to enjoy. It will be analyzed if board membership of incumbents is a mediating factor for the *incumbency effect*.
As part of the research project, we compile a novel, largely hand-collected panel dataset on the boardroom composition of German savings banks with detailed information on board member profiles, along with data on municipal electoral results in Bavaria covering 2,099 municipalities and 79 savings banks over the period from 2006 to 2015.[^1]

## Background
### Public Banks in Crisis?
The collapse of large the US bank Lehman Brothers in 2008 and the global financial crisis brought banks to the attention of the general public and raised academic interest in the relation between banking and politics. However: Public banks, that means the role of politicians *within* banks, are strikingly neglected by the Political Economy literature. This comes as a surprise as they constitute an essential part of the European bank-based financial system, played a central role during the financial crisis[^2] and provide a highly interesting case for Political Economists to study the effects of politicized corporate governance.



### Politicized Sparkassen

## Hypothesis

## Model

## Findings

## Conclusion

[^1]: The presented research project is part of a paper project by Guillermo Rosas (Washington University in St. Louis) and Jonas Markgraf (Hertie School of Governance Berlin).

[^2]: Spanish public savings banks (*cajas*) faltered and dissolved in the course of the bursting Spanish real estate bubble ([link](http://voxeu.org/article/five-lessons-spanish-cajas-debacle-new-euro-wide-supervisor)); similarly, German *Landesbanken* got into serious trouble and were partly consolidated ([link)](http://www.sueddeutsche.de/geld/fehlspekulationen-der-landesbanken-chronologie-einer-krise-1.283250) (in German)). At the same time, German *Sparkassen* weathered the financial crisis well and emerged strengthened from it ([link](http://www.telegraph.co.uk/finance/financialcrisis/3190674/Financial-crisis-boosts-German-banks.html)). This heterogeneous crisis performance of public banks remains largely unexplained and motivates the PhD project of one of the authors.